permalink: /:year:month:day/:title
url: https://dng-3220-m4.github.io/lawn-level-up/
baseurl: /project

# variables
name: ethan maxwell harris' site
description: is it a resume or an admission of failure
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true